export default {
    HOME:"HOME",
    HOURLY:"HOURLY",
    NEARBY:"NEARBY",
    SETTINGS:"SETTINGS",
    WEEKLY:"WEEKLY",
    ABOUT:"ABOUT",
    NEWS:"NEWS",
    TODAYSDETAILS:"TODAYSDETAILS",
    AIRPOLLUTION:"AIRPOLLUTION"
}