export default{
    SWITCH_TEMP:"SWITCH_TEMP",
    SWITCH_WIND:"SWITCH_WIND",
    TOGGLE_NOTIFICATION:"TOGGLE_NOTIFICATION",
    ALERT:"ALERT",
    WEATHER_DETAILS:"WEATHER_DETAILS",
    LOADING:"LOADING",
    POLLUTIONDETAILS:"POLLUTIONDETAILS",
    FIRSTCOLOR:"FIRSTCOLOR",
    SECONDCOLOR:"SECONDTHEME",
    HOURLYTAB:"HOURLYTAB",
    WEEKLYTAB:"WEEKLYTAB"
}